### ISSUE TITLE
npm run build throws up errors

### ISSUE THREAD

**Issue by TheTrio** [dignissimus/lichess-speedrun#30]
```
❯  npm run build

> lichess-speedrun@1.0.0 build /mnt/Github/lichess-speedrun
> scripts/build.sh


src/profile.ts → out...
[!] (plugin typescript) Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
Error: @rollup/plugin-typescript: Could not find module 'tslib', which is required by this plugin. Is it installed?
    at error (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:19344:12)
    at Object.error (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:19994:20)
    at preflight (/mnt/Github/lichess-speedrun/node_modules/@rollup/plugin-typescript/dist/index.js:494:17)
    at Object.buildStart (/mnt/Github/lichess-speedrun/node_modules/@rollup/plugin-typescript/dist/index.js:732:13)
    at /mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:20199:25
    at async Promise.all (index 0)
    at rollupInternal (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:20948:9)
    at build (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup:1508:20)
    at runRollup (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup:1692:21)


> svelte-app@1.0.0 build /mnt/Github/lichess-speedrun/src/ui
> tsc; rollup -c

src/App.ts:1:23 - error TS2307: Cannot find module '../../../out/perfs' or its corresponding type declarations.

1 import { perfs } from "../../../out/perfs"
                        ~~~~~~~~~~~~~~~~~~~~

src/App.ts:2:53 - error TS2307: Cannot find module '../../../out/rating' or its corresponding type declarations.

2 import { displayRating, getRating, setRating } from "../../../out/rating"
                                                      ~~~~~~~~~~~~~~~~~~~~~

tsconfig.json:2:14 - error TS6053: File '@tsconfig/svelte/tsconfig.json' not found.

2   "extends": "@tsconfig/svelte/tsconfig.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.

[!] Error: Cannot find module 'svelte-preprocess'
Require stack:
- /mnt/Github/lichess-speedrun/src/ui/rollup.config.ts
- /mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/loadConfigFile.js
- /mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'svelte-preprocess'
Require stack:
- /mnt/Github/lichess-speedrun/src/ui/rollup.config.ts
- /mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/loadConfigFile.js
- /mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/mnt/Github/lichess-speedrun/src/ui/rollup.config.ts:10:24)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.require.extensions.<computed> [as .ts] (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/loadConfigFile.js:540:20)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
```

I assume this is because some dependencies haven't been installed. Even after manually installing `svelte-preprocess` and `tslib`, it runs into an error(although it does seem to build the output files correctly)

```
> svelte-app@1.0.0 build /mnt/Github/lichess-speedrun/src/ui
> tsc; rollup -c

tsconfig.json:2:14 - error TS6053: File '@tsconfig/svelte/tsconfig.json' not found.

2   "extends": "@tsconfig/svelte/tsconfig.json",
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.


src/main.ts → public/build/bundle.js...
(!) Plugin typescript: @rollup/plugin-typescript TS6053: File '@tsconfig/svelte/tsconfig.json' not found.
[!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options
Error: @rollup/plugin-typescript: Couldn't process compiler options
    at error (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:19344:12)
    at Object.error (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:19994:20)
    at emitParsedOptionsErrors (/mnt/Github/lichess-speedrun/node_modules/@rollup/plugin-typescript/dist/index.js:354:17)
    at Object.buildStart (/mnt/Github/lichess-speedrun/node_modules/@rollup/plugin-typescript/dist/index.js:731:13)
    at /mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:20199:25
    at async Promise.all (index 2)
    at rollupInternal (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/shared/rollup.js:20948:9)
    at build (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup:1508:20)
    at runRollup (/mnt/Github/lichess-speedrun/node_modules/rollup/dist/bin/rollup:1692:21)
```

Any ideas? Excited by the idea of this extension by the way!

**Comment by dignissimus** [comment]
Probably related to #11, I'll have a think and suggest ideas

**Comment by dignissimus** [comment]
Did you run `npm install`?

**Comment by dignissimus** [comment]
Ah, the issue might possibly be the dependencies for the UI aren't installed, maybe running `npm install` in the `src/ui` directory will fix it. If so, I need to make it clear this needs to be done or automate it somewhere, putting the UI dependencies in the main package.json is one solution, and running npm install in the build script is another solution.

**Comment by dignissimus** [comment]
If the above fixes the issue, https://github.com/dignissimus/lichess-speedrun/commit/da55ff1189211a012c4d5a7f26afc74e0b93a77e should be enough

**Comment by TheTrio** [comment]
Yup this does work. Although I'm still having to install `svelte-preprocess` and `tslib` manually. Maybe add those two to the package.json?

**Comment by dignissimus** [comment]
Done in https://github.com/dignissimus/lichess-speedrun/commit/669e9d668457b3585245eb927162873a6b46e83c
